### ISSUE TITLE
Seems like there is a typo at the bottom of the page!

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/cs106s#29]
![image](https://user-images.githubusercontent.com/3037552/152238760-0bdc8b59-724a-4ad6-ac2e-333fd954286c.png)

**Comment by AMMAS1** [comment]
Ahmed Sharaf: this is another typooo

**Comment by ashnakhetan** [comment]
I fixed! Sending a pull request now

**Comment by irawadee-t** [comment]
Sent a pull request!
