### ISSUE TITLE
Fix typo on homepage

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/cs106s#3]
"To learn more about CS + Social Goooooood..."

**Comment by RohanCheri** [comment]
I will work on this!

**Comment by amychang415** [comment]
I will fix the typo

**Comment by lwcarani** [comment]
I will fix the typo too!

**Comment by szhao415** [comment]
I shall fix this typo also :)

**Comment by isaackrementsov** [comment]
I will fix the typo!

**Comment by aprush12** [comment]
Also fixing typo :)

**Comment by DeepanShah** [comment]
This typo has no chance!

**Comment by milesmcc** [comment]
Thanks everyone! This has been fixed.
