### ISSUE TITLE
Add more class recommendations for the CS electives AMA question

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/cs106s#30]
One student asked:

> What are some CS electives you highly recommend? Are there any philosophy or ethics classes that do not have prerequisites and that a STEM major might like?

We answered:

> Tons! You might consider CS 182 (Ethics, Public Policy, and Technological Change), Phil 13N (Justice Across Borders, though it’s not very STEM related), and CS 152 (Trust and Safety Engineering). You might also consider INTLPOL 268D (Online Open Source Investigation) and INTLPOL 268 (Hack Lab).

Perhaps we could add some other class recommendations?

**Comment by mmearly** [comment]
Wow! This looks like a fun task! I'm going to add my own suggestions!

**Comment by eliasapplebaum** [comment]
Thinking about adding this suggestion:

"PHIL20N (Philosophy of AI) is a great winter introsem for frosh CS and SymSys students."

**Comment by ashnakhetan** [comment]
Add: I really liked CME 193 if you're interested in the beginning steps of Machine Learning! For philosophy courses, I'd suggest anything in the SymSys department.

**Comment by btheahs** [comment]
Phil1!
